# Generated by Django 4.2.1 on 2023-05-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestseller_img', models.ImageField(upload_to='bestseller/')),
                ('bestseller_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('bestseller_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category_img', models.ImageField(upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('products_name', models.CharField(blank=True, max_length=50, null=True)),
                ('products_price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('products_review', models.TextField(blank=True, max_length=1000, null=True)),
                ('products_img', models.ImageField(upload_to='product/')),
                ('products_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('products_age', models.TextField(blank=True, max_length=50, null=True)),
                ('products_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.category')),
            ],
        ),
    ]
