# Generated by Django 4.2.1 on 2023-05-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_food_delete_bestseller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='food_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='food_name',
        ),
    ]
