# Generated by Django 4.2.1 on 2023-05-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_rename_category_id_category_food_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_des',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
