# Generated by Django 4.2.1 on 2023-05-10 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_category_alter_food_food_img_food_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('kategori_id', models.AutoField(primary_key=True, serialize=False)),
                ('kategori_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('adoption_id', models.AutoField(primary_key=True, serialize=False)),
                ('adoption_name', models.CharField(blank=True, max_length=50, null=True)),
                ('adoption_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('adoption_img', models.ImageField(upload_to='adoption/')),
                ('adoption_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.kategori')),
            ],
        ),
    ]
