# Generated by Django 4.2.1 on 2023-05-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_categorya_adoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('adopt_id', models.AutoField(primary_key=True, serialize=False)),
                ('adopt_name', models.CharField(blank=True, max_length=50, null=True)),
                ('adopt_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('adopt_img', models.ImageField(upload_to='adopt/')),
                ('adopt_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.kategori')),
            ],
        ),
        migrations.DeleteModel(
            name='Adoption',
        ),
    ]
