# Generated by Django 4.2.1 on 2023-05-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_name',
            new_name='contact_emri',
        ),
    ]
