# Generated by Django 4.2.1 on 2023-05-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_rename_contact_name_contact_contact_emri'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoria',
            name='kategoria_img',
            field=models.ImageField(default=1, upload_to='adopt/'),
            preserve_default=False,
        ),
    ]
