# Generated by Django 4.2.1 on 2023-05-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_subscribedusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribedUsers',
        ),
    ]
